apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rz29j0xwr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rz29j0xwr-go 
  name: rz29j0xwr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rz29j0xwr-go 
